### ISSUE TITLE
get ticket in the authentication advice

### ISSUE THREAD

**Issue by smasue** [dgradecak/alfresco-mvc#2]
Hello Daniel, 

This is Samuel, I have been playing lately with the alfresco mvc. In particular, I was creating controllers with a required level of authentication as admin:
`  @AlfrescoAuthentication(AuthenticationType.ADMIN)`

However I had an authentication exception. Indeed, I had no ticket in the cookies and this piece of code was failing (AuthenticationAdvice:107):
`ticket = (String) parameterMap.get(parameter);`
Due to a cast exception with a String[].

Actually, I was wondering why do you do all this logic with the cookies or the request parameters since you can get all this information with the authenticationService. In the meanwhile I rewrote the method get ticket, in a local branch:
` ticket =  serviceRegistry.getAuthenticationService().getCurrentTicket();`

Cheers,
Sam

**Comment by dgradecak** [comment]
Salut Samuel,

indeed this could probably be skipped today and use directly the authenticationService as you mentioned. There is some historical reasons why it has been done that way.

Could you please create a pull request or do you want me to do it?

**Comment by smasue** [comment]
Yes I'll do a pull request soon, no problem.

Thanks

**Comment by dgradecak** [comment]
Actually those descriptors are just as helpers. In most cases (99,9%) developers would write a webscript with a authentication of at least user. So, instead of using the provided mvc descriptor Anyone can just decalare a descriptor in its own project of course and use whatever authentication is suited, like for any webscript. 

Also, I changed that lately from none to user, simply as I think it is better to have that check in the webscript framework immediately than take care of it in your application, even if alfresco services will fail if there is no access rights.

If you have a different opinion let me know.

**Comment by smasue** [comment]
Thanks for the clarification, it makes a lot of sense. I haven't thought about the possibility of creating my own descriptors. Well for my case I'm part of the 99,9% of the developers so I won't need to. But it's good to know there is a way to overwrite this.
